//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DocumentValidationApp.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class SharedResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SharedResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DocumentValidationApp.Resources.SharedResource", typeof(SharedResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        internal static string Common_Language {
            get {
                return ResourceManager.GetString("Common.Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accepted formats: PDF, PNG, JPG, JPEG (Max size: 10MB).
        /// </summary>
        internal static string DocVal_AcceptedFormats {
            get {
                return ResourceManager.GetString("DocVal.AcceptedFormats", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload a document (PDF, PNG, JPG, JPEG) to validate its type and extract key information. Supported documents: Passport, Driver&apos;s License, ID Card..
        /// </summary>
        internal static string DocVal_CardDescription {
            get {
                return ResourceManager.GetString("DocVal.CardDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload Document for Validation.
        /// </summary>
        internal static string DocVal_CardHeader {
            get {
                return ResourceManager.GetString("DocVal.CardHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description:.
        /// </summary>
        internal static string DocVal_Description {
            get {
                return ResourceManager.GetString("DocVal.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Document Information.
        /// </summary>
        internal static string DocVal_DocumentInformation {
            get {
                return ResourceManager.GetString("DocVal.DocumentInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Document Number:.
        /// </summary>
        internal static string DocVal_DocumentNumber {
            get {
                return ResourceManager.GetString("DocVal.DocumentNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Document Type:.
        /// </summary>
        internal static string DocVal_DocumentType {
            get {
                return ResourceManager.GetString("DocVal.DocumentType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expiration Date:.
        /// </summary>
        internal static string DocVal_ExpirationDate {
            get {
                return ResourceManager.GetString("DocVal.ExpirationDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Extracted Text.
        /// </summary>
        internal static string DocVal_ExtractedText {
            get {
                return ResourceManager.GetString("DocVal.ExtractedText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File size exceeds the maximum allowed size of 10MB. Your file is {0}MB..
        /// </summary>
        internal static string DocVal_FileSizeError {
            get {
                return ResourceManager.GetString("DocVal.FileSizeError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to How it works.
        /// </summary>
        internal static string DocVal_HowItWorks {
            get {
                return ResourceManager.GetString("DocVal.HowItWorks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid file type. Please upload PDF or image files (PNG, JPG, JPEG)..
        /// </summary>
        internal static string DocVal_InvalidFileType {
            get {
                return ResourceManager.GetString("DocVal.InvalidFileType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Issuing Authority:.
        /// </summary>
        internal static string DocVal_IssuingAuthority {
            get {
                return ResourceManager.GetString("DocVal.IssuingAuthority", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No validation messages..
        /// </summary>
        internal static string DocVal_NoValidationMessages {
            get {
                return ResourceManager.GetString("DocVal.NoValidationMessages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AI-powered vision model for comprehensive document analysis. Requires Ollama with qwen3-vl:8b model..
        /// </summary>
        internal static string DocVal_OllamaDescription {
            get {
                return ResourceManager.GetString("DocVal.OllamaDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ollama AI Vision (Qwen3-VL - Advanced image analysis).
        /// </summary>
        internal static string DocVal_OllamaVision {
            get {
                return ResourceManager.GetString("DocVal.OllamaVision", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Advanced AI analysis with better context understanding.
        /// </summary>
        internal static string DocVal_OllamaVisionDesc {
            get {
                return ResourceManager.GetString("DocVal.OllamaVisionDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Document Validation.
        /// </summary>
        internal static string DocVal_PageTitle {
            get {
                return ResourceManager.GetString("DocVal.PageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Privacy.
        /// </summary>
        internal static string DocVal_Privacy {
            get {
                return ResourceManager.GetString("DocVal.Privacy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Documents are processed in memory and not stored on the server. Ollama runs locally on your machine..
        /// </summary>
        internal static string DocVal_PrivacyDesc {
            get {
                return ResourceManager.GetString("DocVal.PrivacyDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Processing document with {0}... Please wait..
        /// </summary>
        internal static string DocVal_Processing {
            get {
                return ResourceManager.GetString("DocVal.Processing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error processing file: {0}.
        /// </summary>
        internal static string DocVal_ProcessingError {
            get {
                return ResourceManager.GetString("DocVal.ProcessingError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Processing Method.
        /// </summary>
        internal static string DocVal_ProcessingMethod {
            get {
                return ResourceManager.GetString("DocVal.ProcessingMethod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Processing Methods.
        /// </summary>
        internal static string DocVal_ProcessingMethods {
            get {
                return ResourceManager.GetString("DocVal.ProcessingMethods", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Document.
        /// </summary>
        internal static string DocVal_SelectDocument {
            get {
                return ResourceManager.GetString("DocVal.SelectDocument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select processing method.
        /// </summary>
        internal static string DocVal_Step1 {
            get {
                return ResourceManager.GetString("DocVal.Step1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload your document.
        /// </summary>
        internal static string DocVal_Step2 {
            get {
                return ResourceManager.GetString("DocVal.Step2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The system analyzes the file.
        /// </summary>
        internal static string DocVal_Step3 {
            get {
                return ResourceManager.GetString("DocVal.Step3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Document type is identified.
        /// </summary>
        internal static string DocVal_Step4 {
            get {
                return ResourceManager.GetString("DocVal.Step4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Key data is extracted (dates, numbers).
        /// </summary>
        internal static string DocVal_Step5 {
            get {
                return ResourceManager.GetString("DocVal.Step5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Validation results are displayed.
        /// </summary>
        internal static string DocVal_Step6 {
            get {
                return ResourceManager.GetString("DocVal.Step6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Traditional OCR for text extraction from document images..
        /// </summary>
        internal static string DocVal_TesseractDescription {
            get {
                return ResourceManager.GetString("DocVal.TesseractDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tesseract OCR (Traditional text extraction).
        /// </summary>
        internal static string DocVal_TesseractOCR {
            get {
                return ResourceManager.GetString("DocVal.TesseractOCR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fast, reliable text extraction.
        /// </summary>
        internal static string DocVal_TesseractOCRDesc {
            get {
                return ResourceManager.GetString("DocVal.TesseractOCRDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Validation Failed.
        /// </summary>
        internal static string DocVal_ValidationFailed {
            get {
                return ResourceManager.GetString("DocVal.ValidationFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Validation Messages.
        /// </summary>
        internal static string DocVal_ValidationMessages {
            get {
                return ResourceManager.GetString("DocVal.ValidationMessages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Validation Results.
        /// </summary>
        internal static string DocVal_ValidationResults {
            get {
                return ResourceManager.GetString("DocVal.ValidationResults", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload your documents (PDF or images) and get instant feedback about document type, expiration dates, and other critical information..
        /// </summary>
        internal static string Home_Description {
            get {
                return ResourceManager.GetString("Home.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Document numbers.
        /// </summary>
        internal static string Home_DocumentNumbers {
            get {
                return ResourceManager.GetString("Home.DocumentNumbers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Driver&apos;s Licenses.
        /// </summary>
        internal static string Home_DriversLicense {
            get {
                return ResourceManager.GetString("Home.DriversLicense", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to State-issued driving permits.
        /// </summary>
        internal static string Home_DriversLicenseDesc {
            get {
                return ResourceManager.GetString("Home.DriversLicenseDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expiration dates.
        /// </summary>
        internal static string Home_ExpirationDates {
            get {
                return ResourceManager.GetString("Home.ExpirationDates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Extracted Data:.
        /// </summary>
        internal static string Home_ExtractedData {
            get {
                return ResourceManager.GetString("Home.ExtractedData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Identity Cards.
        /// </summary>
        internal static string Home_IdentityCards {
            get {
                return ResourceManager.GetString("Home.IdentityCards", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to National ID cards.
        /// </summary>
        internal static string Home_IdentityCardsDesc {
            get {
                return ResourceManager.GetString("Home.IdentityCardsDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Process document images in PNG, JPG, and JPEG formats with OCR support..
        /// </summary>
        internal static string Home_ImageDescription {
            get {
                return ResourceManager.GetString("Home.ImageDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image Processing.
        /// </summary>
        internal static string Home_ImageProcessing {
            get {
                return ResourceManager.GetString("Home.ImageProcessing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Issuing authorities.
        /// </summary>
        internal static string Home_IssuingAuthorities {
            get {
                return ResourceManager.GetString("Home.IssuingAuthorities", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Other Documents.
        /// </summary>
        internal static string Home_OtherDocuments {
            get {
                return ResourceManager.GetString("Home.OtherDocuments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to General document validation.
        /// </summary>
        internal static string Home_OtherDocumentsDesc {
            get {
                return ResourceManager.GetString("Home.OtherDocumentsDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Passports.
        /// </summary>
        internal static string Home_Passports {
            get {
                return ResourceManager.GetString("Home.Passports", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to International travel documents.
        /// </summary>
        internal static string Home_PassportsDesc {
            get {
                return ResourceManager.GetString("Home.PassportsDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Extract text and metadata from PDF documents automatically..
        /// </summary>
        internal static string Home_PDFDescription {
            get {
                return ResourceManager.GetString("Home.PDFDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PDF Support.
        /// </summary>
        internal static string Home_PDFSupport {
            get {
                return ResourceManager.GetString("Home.PDFSupport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Automatically identify document types: Passport, Driver&apos;s License, ID Card..
        /// </summary>
        internal static string Home_SmartDescription {
            get {
                return ResourceManager.GetString("Home.SmartDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Smart Detection.
        /// </summary>
        internal static string Home_SmartDetection {
            get {
                return ResourceManager.GetString("Home.SmartDetection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Validate and extract information from identity documents using AI-powered document analysis.
        /// </summary>
        internal static string Home_Subtitle {
            get {
                return ResourceManager.GetString("Home.Subtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Supported Document Types.
        /// </summary>
        internal static string Home_SupportedDocuments {
            get {
                return ResourceManager.GetString("Home.SupportedDocuments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Document Validation System.
        /// </summary>
        internal static string Home_Title {
            get {
                return ResourceManager.GetString("Home.Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload Document.
        /// </summary>
        internal static string Home_UploadButton {
            get {
                return ResourceManager.GetString("Home.UploadButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Document Validation.
        /// </summary>
        internal static string Nav_AppName {
            get {
                return ResourceManager.GetString("Nav.AppName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Document Validation.
        /// </summary>
        internal static string Nav_DocumentValidation {
            get {
                return ResourceManager.GetString("Nav.DocumentValidation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        internal static string Nav_Home {
            get {
                return ResourceManager.GetString("Nav.Home", resourceCulture);
            }
        }
    }
}
